export const uiText = {
  app: {
    title: 'Home Finder',
    listNav: '一覧',
    createNav: '登録',
    profileNav: 'プロフィール',
  },
  list: {
    title: '物品一覧',
    subtitle: '検索とカテゴリで必要な物品をすばやく絞り込みできます。',
    searchLabel: '検索',
    searchPlaceholder: '名称で検索',
    categoryLabel: 'カテゴリ',
    viewModeLabel: '表示切替',
    emptyTitle: '表示できる物品がありません',
    emptyDescription: '検索条件またはカテゴリを見直してください。',
    loadingTitle: '物品一覧を読み込み中です',
    loadingDescription: 'しばらくお待ちください。',
    failureTitle: '物品一覧の取得に失敗しました',
    failureDescription: 'ネットワーク状態を確認し、再読み込みしてください。',
    validationTitle: '検索条件を見直してください',
    validationDescription: '検索語は1文字以上で入力してください。',
    resetFilter: '条件をクリア',
    reload: '再読み込み',
    createCta: '登録を開始',
    cardView: 'カード',
    tableView: 'テーブル',
    headerName: '名称',
    headerCategory: 'カテゴリ',
    headerQuantity: '数量',
    headerStock: '在庫状態',
  },
  create: {
    title: '物品登録',
    subtitle: '入力内容を確認して登録してください。',
    successToast: '物品を登録しました。',
    submit: '登録する',
    retry: '再試行',
    backToList: '一覧へ戻る',
    fields: {
      name: {
        label: '物品名称',
        placeholder: '例: 卓上ライト',
        helper: '1文字以上で入力してください。',
      },
      quantity: {
        label: '数量',
        placeholder: '1',
        helper: '1以上の整数を入力してください。',
      },
      category: {
        label: 'カテゴリ',
        placeholder: 'カテゴリを選択',
        helper: 'カテゴリを選択してください。',
      },
      manufacturer: {
        label: 'メーカー',
        placeholder: '例: ソニー',
        helper: '任意です。',
      },
      priceInput: {
        label: '価格',
        placeholder: '例: 3980',
        helper: '0以上の数値を入力してください。',
      },
      barcode: {
        label: 'バーコード',
        placeholder: '例: 4901234567890',
        helper: '任意です。',
      },
      description: {
        label: '説明',
        placeholder: '仕様や保管条件などを入力',
        helper: '任意です。',
      },
      note: {
        label: 'メモ',
        placeholder: '任意',
        helper: '任意です。',
      },
    },
  },
  settings: {
    pageTitle: '設定',
    backToList: '一覧へ戻る',
    navButtonLabel: '設定画面へ移動',
    profileSectionHeading: 'プロフィール',
    profileName: '山田 太郎',
    profileRole: '在庫管理者・プレミアムプラン',
    generalSectionHeading: '一般設定',
    items: {
      notifications: {
        label: 'プッシュ通知',
        description: '在庫不足・移動アラートを受け取る',
      },
      appearance: {
        label: '外観',
        description: '現在: ライトモード',
      },
      language: {
        label: '言語',
        description: '日本語',
      },
    },
    dataSectionHeading: 'データ管理',
    dataItems: {
      category: {
        label: 'カテゴリー管理',
        description: '物品のカテゴリーを追加・編集・削除します',
      },
      location: {
        label: '場所（部屋）管理',
        description: '倉庫・部屋・棚を設定する',
      },
      export: {
        label: '在庫エクスポート',
        description: 'CSVまたはExcel形式でダウンロード',
      },
    },
    dangerSectionHeading: '危険ゾーン',
    dangerPurgeLabel: '全在庫データを削除',
    footerVersion: 'v2.4.0 • エンタープライズ版',
    footerCopyright: '© 2024 HomeFinder',
  },
  edit: {
    title: 'アイテム編集',
    subtitle: '内容を変更して更新してください。',
    successToast: '物品を更新しました。',
    submit: '更新する',
  },
  errors: {
    nameRequired: '物品名称は必須です。',
    quantityInvalid: '数量は1以上の整数で入力してください。',
    priceInvalid: '価格は0以上の数値で入力してください。',
    validationSummary: '入力内容に誤りがあります。',
    submitFailed: '物品登録に失敗しました。',
    updateFailed: '物品更新に失敗しました。',
    itemConflict: '同じ名称の物品がすでに登録されています。',
  },
  detail: {
    title: '物品詳細',
    backToList: '一覧へ戻る',
    menuLabel: 'メニュー',
    edit: '編集',
    delete: '削除',
    historyButton: '変更履歴',
    confirmDeleteTitle: '物品を削除しますか？',
    confirmDeleteMessage: 'この操作は取り消せません。物品を削除します。',
    loadingMessage: '読み込み中...',
    notFoundMessage: '指定された物品は存在しません。',
    fetchErrorMessage: '物品詳細の取得に失敗しました。',
    deleteFailMessage: '削除に失敗しました。もう一度お試しください。',
    updateNotFoundMessage: '操作対象の物品が見つかりませんでした。一覧へ戻ります。',
    fieldLabels: {
      name: '名称',
      quantity: '数量',
      category: 'カテゴリ',
      manufacturer: 'メーカー',
      price: '価格',
      barcode: 'バーコード',
      description: '説明',
      note: 'メモ',
      registeredAt: '初回登録日時',
      updatedAt: '最終更新日時',
    },
  },
} as const;
